# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/usermeta.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(960, 640)
        Dialog.setMinimumSize(QtCore.QSize(960, 640))
        Dialog.setMaximumSize(QtCore.QSize(960, 640))
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 40, 900, 550))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_study = QtWidgets.QWidget()
        self.tab_study.setObjectName("tab_study")
        self.identifier = QtWidgets.QLineEdit(self.tab_study)
        self.identifier.setEnabled(False)
        self.identifier.setGeometry(QtCore.QRect(20, 70, 420, 25))
        self.identifier.setStyleSheet("font: italic 10pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.identifier.setText("")
        self.identifier.setObjectName("identifier")
        self.title = QtWidgets.QLineEdit(self.tab_study)
        self.title.setGeometry(QtCore.QRect(20, 120, 420, 25))
        self.title.setText("")
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.tab_study)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_study)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_study)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 131, 16))
        self.label_3.setObjectName("label_3")
        self.submission_date = QtWidgets.QDateEdit(self.tab_study)
        self.submission_date.setGeometry(QtCore.QRect(20, 170, 201, 25))
        self.submission_date.setCalendarPopup(True)
        self.submission_date.setObjectName("submission_date")
        self.label_4 = QtWidgets.QLabel(self.tab_study)
        self.label_4.setGeometry(QtCore.QRect(250, 150, 131, 16))
        self.label_4.setObjectName("label_4")
        self.release_date = QtWidgets.QDateEdit(self.tab_study)
        self.release_date.setGeometry(QtCore.QRect(239, 170, 201, 25))
        self.release_date.setProperty("showGroupSeparator", False)
        self.release_date.setCalendarPopup(True)
        self.release_date.setObjectName("release_date")
        self.label_5 = QtWidgets.QLabel(self.tab_study)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 261, 31))
        self.label_5.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_study)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 261, 31))
        self.label_6.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.pubmed_id = QtWidgets.QLineEdit(self.tab_study)
        self.pubmed_id.setGeometry(QtCore.QRect(20, 280, 131, 25))
        self.pubmed_id.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pubmed_id.setObjectName("pubmed_id")
        self.label_7 = QtWidgets.QLabel(self.tab_study)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 131, 16))
        self.label_7.setObjectName("label_7")
        self.doi = QtWidgets.QLineEdit(self.tab_study)
        self.doi.setGeometry(QtCore.QRect(169, 280, 271, 25))
        self.doi.setObjectName("doi")
        self.label_8 = QtWidgets.QLabel(self.tab_study)
        self.label_8.setGeometry(QtCore.QRect(170, 260, 131, 16))
        self.label_8.setObjectName("label_8")
        self.pub_title = QtWidgets.QLineEdit(self.tab_study)
        self.pub_title.setGeometry(QtCore.QRect(20, 330, 420, 25))
        self.pub_title.setText("")
        self.pub_title.setObjectName("pub_title")
        self.label_9 = QtWidgets.QLabel(self.tab_study)
        self.label_9.setGeometry(QtCore.QRect(20, 310, 131, 16))
        self.label_9.setObjectName("label_9")
        self.combo_status = QtWidgets.QComboBox(self.tab_study)
        self.combo_status.setEnabled(False)
        self.combo_status.setGeometry(QtCore.QRect(20, 380, 421, 25))
        self.combo_status.setObjectName("combo_status")
        self.combo_status.addItem("")
        self.label_10 = QtWidgets.QLabel(self.tab_study)
        self.label_10.setGeometry(QtCore.QRect(20, 360, 131, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_study)
        self.label_11.setGeometry(QtCore.QRect(470, 50, 211, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_study)
        self.label_12.setGeometry(QtCore.QRect(470, 230, 261, 31))
        self.label_12.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.first_name = QtWidgets.QLineEdit(self.tab_study)
        self.first_name.setGeometry(QtCore.QRect(470, 280, 130, 25))
        self.first_name.setObjectName("first_name")
        self.mid = QtWidgets.QLineEdit(self.tab_study)
        self.mid.setGeometry(QtCore.QRect(620, 280, 45, 25))
        self.mid.setObjectName("mid")
        self.last_name = QtWidgets.QLineEdit(self.tab_study)
        self.last_name.setGeometry(QtCore.QRect(685, 280, 195, 25))
        self.last_name.setObjectName("last_name")
        self.label_13 = QtWidgets.QLabel(self.tab_study)
        self.label_13.setGeometry(QtCore.QRect(470, 260, 131, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_study)
        self.label_14.setGeometry(QtCore.QRect(685, 260, 131, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_study)
        self.label_15.setGeometry(QtCore.QRect(600, 260, 71, 16))
        self.label_15.setScaledContents(False)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.phone = QtWidgets.QLineEdit(self.tab_study)
        self.phone.setGeometry(QtCore.QRect(470, 330, 195, 25))
        self.phone.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly)
        self.phone.setObjectName("phone")
        self.label_16 = QtWidgets.QLabel(self.tab_study)
        self.label_16.setGeometry(QtCore.QRect(470, 310, 131, 25))
        self.label_16.setObjectName("label_16")
        self.mail = QtWidgets.QLineEdit(self.tab_study)
        self.mail.setGeometry(QtCore.QRect(685, 330, 195, 25))
        self.mail.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.mail.setObjectName("mail")
        self.label_17 = QtWidgets.QLabel(self.tab_study)
        self.label_17.setGeometry(QtCore.QRect(685, 310, 131, 25))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_study)
        self.label_18.setGeometry(QtCore.QRect(470, 360, 131, 25))
        self.label_18.setObjectName("label_18")
        self.line = QtWidgets.QFrame(self.tab_study)
        self.line.setGeometry(QtCore.QRect(445, 260, 20, 241))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.combo_roles = QtWidgets.QComboBox(self.tab_study)
        self.combo_roles.setEnabled(False)
        self.combo_roles.setGeometry(QtCore.QRect(470, 480, 195, 25))
        self.combo_roles.setObjectName("combo_roles")
        self.combo_roles.addItem("")
        self.label_20 = QtWidgets.QLabel(self.tab_study)
        self.label_20.setGeometry(QtCore.QRect(470, 460, 131, 25))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_study)
        self.label_21.setGeometry(QtCore.QRect(685, 360, 131, 25))
        self.label_21.setObjectName("label_21")
        self.adress = QtWidgets.QPlainTextEdit(self.tab_study)
        self.adress.setGeometry(QtCore.QRect(685, 379, 195, 131))
        self.adress.setObjectName("adress")
        self.description = QtWidgets.QTextEdit(self.tab_study)
        self.description.setGeometry(QtCore.QRect(470, 70, 411, 121))
        self.description.setObjectName("description")
        self.fax = QtWidgets.QLineEdit(self.tab_study)
        self.fax.setGeometry(QtCore.QRect(470, 380, 195, 25))
        self.fax.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly)
        self.fax.setObjectName("fax")
        self.label_23 = QtWidgets.QLabel(self.tab_study)
        self.label_23.setGeometry(QtCore.QRect(470, 410, 131, 25))
        self.label_23.setObjectName("label_23")
        self.affiliation = QtWidgets.QLineEdit(self.tab_study)
        self.affiliation.setGeometry(QtCore.QRect(470, 430, 195, 25))
        self.affiliation.setObjectName("affiliation")
        self.label_51 = QtWidgets.QLabel(self.tab_study)
        self.label_51.setGeometry(QtCore.QRect(20, 410, 131, 16))
        self.label_51.setObjectName("label_51")
        self.authors_list = QtWidgets.QTextEdit(self.tab_study)
        self.authors_list.setGeometry(QtCore.QRect(20, 430, 421, 81))
        self.authors_list.setObjectName("authors_list")
        self.status = QtWidgets.QLineEdit(self.tab_study)
        self.status.setGeometry(QtCore.QRect(20, 370, 421, 41))
        self.status.setFrame(False)
        self.status.setObjectName("status")
        self.roles = QtWidgets.QLineEdit(self.tab_study)
        self.roles.setEnabled(True)
        self.roles.setGeometry(QtCore.QRect(470, 480, 195, 25))
        self.roles.setStyleSheet("color: rgb(0, 0, 0);")
        self.roles.setFrame(False)
        self.roles.setObjectName("roles")
        self.roles.raise_()
        self.status.raise_()
        self.identifier.raise_()
        self.title.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.submission_date.raise_()
        self.label_4.raise_()
        self.release_date.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.pubmed_id.raise_()
        self.label_7.raise_()
        self.doi.raise_()
        self.label_8.raise_()
        self.pub_title.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.first_name.raise_()
        self.mid.raise_()
        self.last_name.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.phone.raise_()
        self.label_16.raise_()
        self.mail.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.line.raise_()
        self.combo_roles.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.adress.raise_()
        self.description.raise_()
        self.fax.raise_()
        self.label_23.raise_()
        self.affiliation.raise_()
        self.label_51.raise_()
        self.authors_list.raise_()
        self.combo_status.raise_()
        self.label_10.raise_()
        self.tabWidget.addTab(self.tab_study, "")
        self.tab_investigation = QtWidgets.QWidget()
        self.tab_investigation.setObjectName("tab_investigation")
        self.label_19 = QtWidgets.QLabel(self.tab_investigation)
        self.label_19.setGeometry(QtCore.QRect(20, 150, 131, 16))
        self.label_19.setObjectName("label_19")
        self.submission_date_2 = QtWidgets.QDateEdit(self.tab_investigation)
        self.submission_date_2.setGeometry(QtCore.QRect(20, 170, 201, 25))
        self.submission_date_2.setObjectName("submission_date_2")
        self.release_date_2 = QtWidgets.QDateEdit(self.tab_investigation)
        self.release_date_2.setGeometry(QtCore.QRect(239, 170, 201, 25))
        self.release_date_2.setObjectName("release_date_2")
        self.label_24 = QtWidgets.QLabel(self.tab_investigation)
        self.label_24.setGeometry(QtCore.QRect(470, 50, 211, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_investigation)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 261, 21))
        self.label_25.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.identifier_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.identifier_2.setEnabled(False)
        self.identifier_2.setGeometry(QtCore.QRect(20, 70, 420, 25))
        self.identifier_2.setStyleSheet("font: italic 10pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.identifier_2.setText("")
        self.identifier_2.setObjectName("identifier_2")
        self.description_2 = QtWidgets.QTextEdit(self.tab_investigation)
        self.description_2.setGeometry(QtCore.QRect(470, 70, 411, 121))
        self.description_2.setObjectName("description_2")
        self.label_26 = QtWidgets.QLabel(self.tab_investigation)
        self.label_26.setGeometry(QtCore.QRect(250, 150, 131, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_investigation)
        self.label_27.setEnabled(False)
        self.label_27.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label_27.setObjectName("label_27")
        self.title_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.title_2.setGeometry(QtCore.QRect(20, 120, 420, 25))
        self.title_2.setText("")
        self.title_2.setObjectName("title_2")
        self.label_28 = QtWidgets.QLabel(self.tab_investigation)
        self.label_28.setGeometry(QtCore.QRect(20, 100, 131, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_investigation)
        self.label_29.setGeometry(QtCore.QRect(470, 230, 261, 31))
        self.label_29.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_29.setObjectName("label_29")
        self.pubmed_id_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.pubmed_id_2.setGeometry(QtCore.QRect(20, 280, 131, 25))
        self.pubmed_id_2.setObjectName("pubmed_id_2")
        self.line_2 = QtWidgets.QFrame(self.tab_investigation)
        self.line_2.setGeometry(QtCore.QRect(445, 260, 20, 251))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_30 = QtWidgets.QLabel(self.tab_investigation)
        self.label_30.setGeometry(QtCore.QRect(600, 260, 71, 16))
        self.label_30.setScaledContents(False)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.last_name_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.last_name_2.setGeometry(QtCore.QRect(685, 280, 195, 25))
        self.last_name_2.setObjectName("last_name_2")
        self.affiliation_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.affiliation_2.setGeometry(QtCore.QRect(470, 430, 195, 25))
        self.affiliation_2.setObjectName("affiliation_2")
        self.first_name_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.first_name_2.setGeometry(QtCore.QRect(470, 280, 131, 25))
        self.first_name_2.setObjectName("first_name_2")
        self.label_31 = QtWidgets.QLabel(self.tab_investigation)
        self.label_31.setGeometry(QtCore.QRect(470, 260, 131, 16))
        self.label_31.setObjectName("label_31")
        self.combo_status_2 = QtWidgets.QComboBox(self.tab_investigation)
        self.combo_status_2.setEnabled(False)
        self.combo_status_2.setGeometry(QtCore.QRect(20, 380, 421, 25))
        self.combo_status_2.setMaxVisibleItems(10)
        self.combo_status_2.setObjectName("combo_status_2")
        self.combo_status_2.addItem("")
        self.label_32 = QtWidgets.QLabel(self.tab_investigation)
        self.label_32.setGeometry(QtCore.QRect(20, 360, 131, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_investigation)
        self.label_33.setGeometry(QtCore.QRect(20, 230, 261, 21))
        self.label_33.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_investigation)
        self.label_34.setGeometry(QtCore.QRect(470, 460, 131, 25))
        self.label_34.setObjectName("label_34")
        self.phone_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.phone_2.setGeometry(QtCore.QRect(470, 330, 195, 25))
        self.phone_2.setObjectName("phone_2")
        self.label_35 = QtWidgets.QLabel(self.tab_investigation)
        self.label_35.setGeometry(QtCore.QRect(685, 360, 131, 25))
        self.label_35.setObjectName("label_35")
        self.mid_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.mid_2.setGeometry(QtCore.QRect(620, 280, 45, 25))
        self.mid_2.setObjectName("mid_2")
        self.label_36 = QtWidgets.QLabel(self.tab_investigation)
        self.label_36.setGeometry(QtCore.QRect(20, 260, 131, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_investigation)
        self.label_37.setGeometry(QtCore.QRect(470, 410, 131, 25))
        self.label_37.setObjectName("label_37")
        self.mail_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.mail_2.setGeometry(QtCore.QRect(685, 330, 195, 25))
        self.mail_2.setObjectName("mail_2")
        self.doi_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.doi_2.setGeometry(QtCore.QRect(169, 280, 271, 25))
        self.doi_2.setObjectName("doi_2")
        self.fax_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.fax_2.setGeometry(QtCore.QRect(470, 380, 195, 25))
        self.fax_2.setObjectName("fax_2")
        self.label_38 = QtWidgets.QLabel(self.tab_investigation)
        self.label_38.setGeometry(QtCore.QRect(470, 310, 131, 25))
        self.label_38.setObjectName("label_38")
        self.pub_title_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.pub_title_2.setGeometry(QtCore.QRect(20, 330, 420, 25))
        self.pub_title_2.setText("")
        self.pub_title_2.setObjectName("pub_title_2")
        self.label_39 = QtWidgets.QLabel(self.tab_investigation)
        self.label_39.setGeometry(QtCore.QRect(20, 310, 131, 16))
        self.label_39.setObjectName("label_39")
        self.adress_2 = QtWidgets.QPlainTextEdit(self.tab_investigation)
        self.adress_2.setGeometry(QtCore.QRect(685, 379, 195, 131))
        self.adress_2.setObjectName("adress_2")
        self.label_40 = QtWidgets.QLabel(self.tab_investigation)
        self.label_40.setGeometry(QtCore.QRect(470, 360, 131, 25))
        self.label_40.setObjectName("label_40")
        self.combo_roles_2 = QtWidgets.QComboBox(self.tab_investigation)
        self.combo_roles_2.setEnabled(False)
        self.combo_roles_2.setGeometry(QtCore.QRect(470, 480, 195, 25))
        self.combo_roles_2.setObjectName("combo_roles_2")
        self.combo_roles_2.addItem("")
        self.label_41 = QtWidgets.QLabel(self.tab_investigation)
        self.label_41.setGeometry(QtCore.QRect(685, 260, 131, 16))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_investigation)
        self.label_42.setGeometry(QtCore.QRect(685, 310, 131, 25))
        self.label_42.setObjectName("label_42")
        self.roles_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.roles_2.setEnabled(True)
        self.roles_2.setGeometry(QtCore.QRect(470, 480, 195, 25))
        self.roles_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.roles_2.setFrame(False)
        self.roles_2.setObjectName("roles_2")
        self.label_43 = QtWidgets.QLabel(self.tab_investigation)
        self.label_43.setGeometry(QtCore.QRect(170, 260, 131, 16))
        self.label_43.setObjectName("label_43")
        self.contact_sameas = QtWidgets.QCheckBox(self.tab_investigation)
        self.contact_sameas.setGeometry(QtCore.QRect(710, 230, 171, 21))
        self.contact_sameas.setObjectName("contact_sameas")
        self.pub_sameas = QtWidgets.QCheckBox(self.tab_investigation)
        self.pub_sameas.setGeometry(QtCore.QRect(270, 230, 171, 21))
        self.pub_sameas.setChecked(False)
        self.pub_sameas.setObjectName("pub_sameas")
        self.label_52 = QtWidgets.QLabel(self.tab_investigation)
        self.label_52.setGeometry(QtCore.QRect(20, 410, 131, 16))
        self.label_52.setObjectName("label_52")
        self.authors_list_2 = QtWidgets.QTextEdit(self.tab_investigation)
        self.authors_list_2.setEnabled(True)
        self.authors_list_2.setGeometry(QtCore.QRect(20, 430, 421, 81))
        self.authors_list_2.setStyleSheet("")
        self.authors_list_2.setObjectName("authors_list_2")
        self.status_2 = QtWidgets.QLineEdit(self.tab_investigation)
        self.status_2.setGeometry(QtCore.QRect(20, 370, 421, 41))
        self.status_2.setFrame(False)
        self.status_2.setObjectName("status_2")
        self.roles_2.raise_()
        self.status_2.raise_()
        self.label_19.raise_()
        self.submission_date_2.raise_()
        self.release_date_2.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.identifier_2.raise_()
        self.description_2.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.title_2.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.pubmed_id_2.raise_()
        self.line_2.raise_()
        self.label_30.raise_()
        self.last_name_2.raise_()
        self.affiliation_2.raise_()
        self.first_name_2.raise_()
        self.label_31.raise_()
        self.combo_status_2.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.phone_2.raise_()
        self.label_35.raise_()
        self.mid_2.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.mail_2.raise_()
        self.doi_2.raise_()
        self.fax_2.raise_()
        self.label_38.raise_()
        self.pub_title_2.raise_()
        self.label_39.raise_()
        self.adress_2.raise_()
        self.label_40.raise_()
        self.combo_roles_2.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.contact_sameas.raise_()
        self.pub_sameas.raise_()
        self.label_52.raise_()
        self.authors_list_2.raise_()
        self.tabWidget.addTab(self.tab_investigation, "")
        self.tab_misc = QtWidgets.QWidget()
        self.tab_misc.setEnabled(True)
        self.tab_misc.setObjectName("tab_misc")
        self.label_44 = QtWidgets.QLabel(self.tab_misc)
        self.label_44.setGeometry(QtCore.QRect(20, 20, 261, 16))
        self.label_44.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_misc)
        self.label_45.setGeometry(QtCore.QRect(20, 50, 130, 16))
        self.label_45.setObjectName("label_45")
        self.id_organism = QtWidgets.QLineEdit(self.tab_misc)
        self.id_organism.setGeometry(QtCore.QRect(190, 70, 181, 25))
        self.id_organism.setText("")
        self.id_organism.setObjectName("id_organism")
        self.label_46 = QtWidgets.QLabel(self.tab_misc)
        self.label_46.setGeometry(QtCore.QRect(20, 110, 131, 16))
        self.label_46.setObjectName("label_46")
        self.id_organism_variant = QtWidgets.QLineEdit(self.tab_misc)
        self.id_organism_variant.setGeometry(QtCore.QRect(190, 130, 181, 25))
        self.id_organism_variant.setText("")
        self.id_organism_variant.setObjectName("id_organism_variant")
        self.id_organism_part = QtWidgets.QLineEdit(self.tab_misc)
        self.id_organism_part.setGeometry(QtCore.QRect(190, 190, 181, 25))
        self.id_organism_part.setText("")
        self.id_organism_part.setObjectName("id_organism_part")
        self.label_47 = QtWidgets.QLabel(self.tab_misc)
        self.label_47.setGeometry(QtCore.QRect(20, 170, 131, 16))
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(self.tab_misc)
        self.label_50.setGeometry(QtCore.QRect(20, 250, 261, 31))
        self.label_50.setStyleSheet("font: 12pt url(:/fonts/assets/fonts/Verdana.ttf);")
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_50.setObjectName("label_50")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_misc)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 290, 851, 211))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.sample_collect = QtWidgets.QWidget()
        self.sample_collect.setObjectName("sample_collect")
        self.sample_collect_desc = QtWidgets.QTextEdit(self.sample_collect)
        self.sample_collect_desc.setGeometry(QtCore.QRect(0, 0, 847, 180))
        self.sample_collect_desc.setMinimumSize(QtCore.QSize(847, 180))
        self.sample_collect_desc.setMaximumSize(QtCore.QSize(847, 180))
        self.sample_collect_desc.setObjectName("sample_collect_desc")
        self.tabWidget_2.addTab(self.sample_collect, "")
        self.extraction = QtWidgets.QWidget()
        self.extraction.setObjectName("extraction")
        self.extraction_desc = QtWidgets.QTextEdit(self.extraction)
        self.extraction_desc.setGeometry(QtCore.QRect(0, 0, 847, 180))
        self.extraction_desc.setMinimumSize(QtCore.QSize(847, 180))
        self.extraction_desc.setMaximumSize(QtCore.QSize(847, 180))
        self.extraction_desc.setObjectName("extraction_desc")
        self.tabWidget_2.addTab(self.extraction, "")
        self.chroma = QtWidgets.QWidget()
        self.chroma.setObjectName("chroma")
        self.chroma_desc = QtWidgets.QTextEdit(self.chroma)
        self.chroma_desc.setGeometry(QtCore.QRect(0, 0, 847, 180))
        self.chroma_desc.setMinimumSize(QtCore.QSize(847, 180))
        self.chroma_desc.setMaximumSize(QtCore.QSize(847, 180))
        self.chroma_desc.setObjectName("chroma_desc")
        self.tabWidget_2.addTab(self.chroma, "")
        self.mass_spec = QtWidgets.QWidget()
        self.mass_spec.setObjectName("mass_spec")
        self.mass_spec_desc = QtWidgets.QTextEdit(self.mass_spec)
        self.mass_spec_desc.setGeometry(QtCore.QRect(0, 0, 847, 180))
        self.mass_spec_desc.setMinimumSize(QtCore.QSize(847, 180))
        self.mass_spec_desc.setMaximumSize(QtCore.QSize(847, 180))
        self.mass_spec_desc.setObjectName("mass_spec_desc")
        self.tabWidget_2.addTab(self.mass_spec, "")
        self.data_trans = QtWidgets.QWidget()
        self.data_trans.setObjectName("data_trans")
        self.data_trans_desc = QtWidgets.QTextEdit(self.data_trans)
        self.data_trans_desc.setGeometry(QtCore.QRect(0, 0, 847, 180))
        self.data_trans_desc.setMinimumSize(QtCore.QSize(847, 180))
        self.data_trans_desc.setMaximumSize(QtCore.QSize(847, 180))
        self.data_trans_desc.setObjectName("data_trans_desc")
        self.tabWidget_2.addTab(self.data_trans, "")
        self.metabo_id = QtWidgets.QWidget()
        self.metabo_id.setObjectName("metabo_id")
        self.metabo_id_desc = QtWidgets.QTextEdit(self.metabo_id)
        self.metabo_id_desc.setGeometry(QtCore.QRect(0, 0, 847, 180))
        self.metabo_id_desc.setMinimumSize(QtCore.QSize(847, 180))
        self.metabo_id_desc.setMaximumSize(QtCore.QSize(847, 180))
        self.metabo_id_desc.setObjectName("metabo_id_desc")
        self.tabWidget_2.addTab(self.metabo_id, "")
        self.search_organism = QtWidgets.QPushButton(self.tab_misc)
        self.search_organism.setGeometry(QtCore.QRect(380, 70, 41, 26))
        font = QtGui.QFont()
        font.setFamily("EBI-Conceptual")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_organism.setFont(font)
        self.search_organism.setStyleSheet("font: 14pt \":/fonts/assets/fonts/EBI-Conceptual.ttf\";\n"
"font-family: \"EBI-Conceptual\";")
        self.search_organism.setObjectName("search_organism")
        self.search_organism_variant = QtWidgets.QPushButton(self.tab_misc)
        self.search_organism_variant.setGeometry(QtCore.QRect(380, 130, 41, 26))
        font = QtGui.QFont()
        font.setFamily("EBI-Conceptual")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_organism_variant.setFont(font)
        self.search_organism_variant.setStyleSheet("font: 14pt \":/fonts/assets/fonts/EBI-Conceptual.ttf\";\n"
"font-family: \"EBI-Conceptual\";")
        self.search_organism_variant.setObjectName("search_organism_variant")
        self.search_organism_part = QtWidgets.QPushButton(self.tab_misc)
        self.search_organism_part.setGeometry(QtCore.QRect(380, 190, 41, 26))
        font = QtGui.QFont()
        font.setFamily("EBI-Conceptual")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_organism_part.setFont(font)
        self.search_organism_part.setStyleSheet("font: 14pt \":/fonts/assets/fonts/EBI-Conceptual.ttf\";\n"
"font-family: \"EBI-Conceptual\";")
        self.search_organism_part.setObjectName("search_organism_part")
        self.comboBox = QtWidgets.QComboBox(self.tab_misc)
        self.comboBox.setGeometry(QtCore.QRect(20, 70, 161, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_misc)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 130, 161, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_misc)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 190, 161, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.tabWidget.addTab(self.tab_misc, "")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 960, 30))
        self.frame.setStyleSheet("background: rgb(11,123,125);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(30, 610, 311, 16))
        self.label_22.setObjectName("label_22")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(600, 606, 331, 26))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        self.combo_status_2.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.identifier, self.title)
        Dialog.setTabOrder(self.title, self.submission_date)
        Dialog.setTabOrder(self.submission_date, self.release_date)
        Dialog.setTabOrder(self.release_date, self.description)
        Dialog.setTabOrder(self.description, self.pubmed_id)
        Dialog.setTabOrder(self.pubmed_id, self.doi)
        Dialog.setTabOrder(self.doi, self.pub_title)
        Dialog.setTabOrder(self.pub_title, self.combo_status)
        Dialog.setTabOrder(self.combo_status, self.authors_list)
        Dialog.setTabOrder(self.authors_list, self.first_name)
        Dialog.setTabOrder(self.first_name, self.mid)
        Dialog.setTabOrder(self.mid, self.last_name)
        Dialog.setTabOrder(self.last_name, self.phone)
        Dialog.setTabOrder(self.phone, self.mail)
        Dialog.setTabOrder(self.mail, self.fax)
        Dialog.setTabOrder(self.fax, self.affiliation)
        Dialog.setTabOrder(self.affiliation, self.combo_roles)
        Dialog.setTabOrder(self.combo_roles, self.adress)
        Dialog.setTabOrder(self.adress, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.identifier_2)
        Dialog.setTabOrder(self.identifier_2, self.title_2)
        Dialog.setTabOrder(self.title_2, self.submission_date_2)
        Dialog.setTabOrder(self.submission_date_2, self.release_date_2)
        Dialog.setTabOrder(self.release_date_2, self.description_2)
        Dialog.setTabOrder(self.description_2, self.pub_sameas)
        Dialog.setTabOrder(self.pub_sameas, self.pubmed_id_2)
        Dialog.setTabOrder(self.pubmed_id_2, self.doi_2)
        Dialog.setTabOrder(self.doi_2, self.pub_title_2)
        Dialog.setTabOrder(self.pub_title_2, self.combo_status_2)
        Dialog.setTabOrder(self.combo_status_2, self.authors_list_2)
        Dialog.setTabOrder(self.authors_list_2, self.contact_sameas)
        Dialog.setTabOrder(self.contact_sameas, self.first_name_2)
        Dialog.setTabOrder(self.first_name_2, self.mid_2)
        Dialog.setTabOrder(self.mid_2, self.last_name_2)
        Dialog.setTabOrder(self.last_name_2, self.phone_2)
        Dialog.setTabOrder(self.phone_2, self.mail_2)
        Dialog.setTabOrder(self.mail_2, self.fax_2)
        Dialog.setTabOrder(self.fax_2, self.affiliation_2)
        Dialog.setTabOrder(self.affiliation_2, self.combo_roles_2)
        Dialog.setTabOrder(self.combo_roles_2, self.adress_2)
        Dialog.setTabOrder(self.adress_2, self.id_organism)
        Dialog.setTabOrder(self.id_organism, self.id_organism_variant)
        Dialog.setTabOrder(self.id_organism_variant, self.id_organism_part)
        Dialog.setTabOrder(self.id_organism_part, self.tabWidget_2)
        Dialog.setTabOrder(self.tabWidget_2, self.extraction_desc)
        Dialog.setTabOrder(self.extraction_desc, self.chroma_desc)
        Dialog.setTabOrder(self.chroma_desc, self.mass_spec_desc)
        Dialog.setTabOrder(self.mass_spec_desc, self.data_trans_desc)
        Dialog.setTabOrder(self.data_trans_desc, self.metabo_id_desc)
        Dialog.setTabOrder(self.metabo_id_desc, self.roles_2)
        Dialog.setTabOrder(self.roles_2, self.sample_collect_desc)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Additional Metadata"))
        self.identifier.setPlaceholderText(_translate("Dialog", "will use study identifier name from main window"))
        self.label.setText(_translate("Dialog", "Identifier"))
        self.label_2.setText(_translate("Dialog", "Title *"))
        self.label_3.setText(_translate("Dialog", "Submission date"))
        self.submission_date.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_4.setText(_translate("Dialog", "Release date"))
        self.release_date.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_5.setText(_translate("Dialog", "Study"))
        self.label_6.setText(_translate("Dialog", "Study Publication"))
        self.pubmed_id.setPlaceholderText(_translate("Dialog", "e.g. 26496010"))
        self.label_7.setText(_translate("Dialog", "PubMed identifier"))
        self.doi.setPlaceholderText(_translate("Dialog", "e.g.  10.1016/j.jhep.2013.12.002"))
        self.label_8.setText(_translate("Dialog", "DOI"))
        self.label_9.setText(_translate("Dialog", "Title"))
        self.combo_status.setItemText(0, _translate("Dialog", "connecting to PSO <sparontologies.net/ontologies/pso>"))
        self.label_10.setText(_translate("Dialog", "Status"))
        self.label_11.setText(_translate("Dialog", "Description *"))
        self.label_12.setText(_translate("Dialog", "Study Contact *"))
        self.label_13.setText(_translate("Dialog", "First Name"))
        self.label_14.setText(_translate("Dialog", "Last Name"))
        self.label_15.setText(_translate("Dialog", "Mid Initials"))
        self.label_16.setText(_translate("Dialog", "Telephone"))
        self.label_17.setText(_translate("Dialog", "Mail"))
        self.label_18.setText(_translate("Dialog", "Fax"))
        self.combo_roles.setItemText(0, _translate("Dialog", "connecting to PRO <...>"))
        self.label_20.setText(_translate("Dialog", "Role"))
        self.label_21.setText(_translate("Dialog", "Adress"))
        self.label_23.setText(_translate("Dialog", "Affiliation"))
        self.label_51.setText(_translate("Dialog", "Authors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_study), _translate("Dialog", "Study"))
        self.label_19.setText(_translate("Dialog", "Submission date"))
        self.submission_date_2.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.release_date_2.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.label_24.setText(_translate("Dialog", "Description"))
        self.label_25.setText(_translate("Dialog", "Investigation"))
        self.identifier_2.setPlaceholderText(_translate("Dialog", "will use study identifier name from main window"))
        self.label_26.setText(_translate("Dialog", "Release date"))
        self.label_27.setText(_translate("Dialog", "Identifier"))
        self.label_28.setText(_translate("Dialog", "Title"))
        self.label_29.setText(_translate("Dialog", "Investigation Contact"))
        self.pubmed_id_2.setPlaceholderText(_translate("Dialog", "e.g. 26496010"))
        self.label_30.setText(_translate("Dialog", "Mid Initials"))
        self.label_31.setText(_translate("Dialog", "First Name"))
        self.combo_status_2.setCurrentText(_translate("Dialog", "connecting to PSO <sparontologies.net/ontologies/pso>"))
        self.combo_status_2.setItemText(0, _translate("Dialog", "connecting to PSO <sparontologies.net/ontologies/pso>"))
        self.label_32.setText(_translate("Dialog", "Status"))
        self.label_33.setText(_translate("Dialog", "Investigation Publication"))
        self.label_34.setText(_translate("Dialog", "Role"))
        self.label_35.setText(_translate("Dialog", "Adress"))
        self.label_36.setText(_translate("Dialog", "PubMed identifier"))
        self.label_37.setText(_translate("Dialog", "Affiliation"))
        self.doi_2.setPlaceholderText(_translate("Dialog", "e.g.  10.1016/j.jhep.2013.12.002"))
        self.label_38.setText(_translate("Dialog", "Telephone"))
        self.label_39.setText(_translate("Dialog", "Title"))
        self.label_40.setText(_translate("Dialog", "Fax"))
        self.combo_roles_2.setItemText(0, _translate("Dialog", "connecting to PRO <...>"))
        self.label_41.setText(_translate("Dialog", "Last Name"))
        self.label_42.setText(_translate("Dialog", "Mail"))
        self.label_43.setText(_translate("Dialog", "DOI"))
        self.contact_sameas.setText(_translate("Dialog", "Same as Study"))
        self.pub_sameas.setText(_translate("Dialog", "Same as Study"))
        self.label_52.setText(_translate("Dialog", "Authors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_investigation), _translate("Dialog", "Investigation"))
        self.label_44.setText(_translate("Dialog", "Characteristics *"))
        self.label_45.setText(_translate("Dialog", "Organism"))
        self.id_organism.setPlaceholderText(_translate("Dialog", "ID (numbers only)"))
        self.label_46.setText(_translate("Dialog", "Organism variant"))
        self.id_organism_variant.setPlaceholderText(_translate("Dialog", "ID (numbers only)"))
        self.id_organism_part.setPlaceholderText(_translate("Dialog", "ID (numbers only)"))
        self.label_47.setText(_translate("Dialog", "Organism part"))
        self.label_50.setText(_translate("Dialog", "Protocols description *"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.sample_collect), _translate("Dialog", "Sample collection"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.extraction), _translate("Dialog", "Extraction"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.chroma), _translate("Dialog", "Chromatography"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.mass_spec), _translate("Dialog", "Mass spectrometry"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.data_trans), _translate("Dialog", "Data transformation"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.metabo_id), _translate("Dialog", "Metabolite identification"))
        self.search_organism.setText(_translate("Dialog", "o"))
        self.search_organism_variant.setText(_translate("Dialog", "o"))
        self.search_organism_part.setText(_translate("Dialog", "o"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_misc), _translate("Dialog", "Experiments"))
        self.label_22.setText(_translate("Dialog", "*: Fields required by a MetaboLights study"))

import resources_rc
